[workspace]
members = [
    "millenium-assets",
    "millenium-desktop",
    "millenium-core",
]

[profile.release]
codegen-units = 1
debug = true
incremental = false
lto = true
opt-level = "s"
panic = "abort"
