[workspace]
members = [
    "core",
    "desktop/assets",
    "desktop/backend",
    "desktop/frontend",
    "desktop/tools/expand-template",
    "post-office",
]

[profile.release]
codegen-units = 1
debug = true
incremental = false
lto = true
opt-level = "s"
panic = "abort"
