name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.71.1
        components: clippy, rustfmt
    - name: Set up Rust cache
      uses: Swatinem/rust-cache@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: |
        set -eux
        sudo apt-get update
        sudo apt-get install -y \
           libasound2-dev \
           libgtk-3-dev \
           libjavascriptcoregtk-4.1-dev \
           libsoup-3.0-dev \
           libwebkit2gtk-4.1-dev \
           libxdo-dev
    - name: Code Style
      run: cargo fmt --check
    - name: Tests
      run: cargo test --all-features
    - name: Clippy
      run: cargo clippy --all-features

  test-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.71.1
    - name: Set up Rust cache
      uses: Swatinem/rust-cache@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Tests
      shell: bash
      run: cargo test --all-features
