name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.72.0
        components: clippy, rustfmt
        targets: wasm32-unknown-unknown
    - name: Set up Rust cache
      uses: Swatinem/rust-cache@v2
    - name: Install dependencies
      run: |
        set -eux
        sudo apt-get update
        sudo apt-get install -y \
           libasound2-dev \
           libgtk-3-dev \
           libwebkit2gtk-4.1-dev \
           libxdo-dev
    - name: Install just
      uses: taiki-e/install-action@v2
      with:
        tool: just
    - name: Install Trunk
      uses: jetli/trunk-action@v0.4.0
      with:
        version: "latest"
    - name: Test
      run: just test

  test-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: 1.72.0
    - name: Set up Rust cache
      uses: Swatinem/rust-cache@v2
    - name: Tests
      shell: bash
      run: |
        set -eux
        mkdir -p desktop/frontend/build/static
        echo -n "test" > desktop/frontend/build/static/test_asset.txt
        cargo test --all-features
